package com.ll.po;

public class Active {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active.a_id
     *
     * @mbggenerated
     */
    private Integer aId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active.c_id
     *
     * @mbggenerated
     */
    private Integer cId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active.a_name
     *
     * @mbggenerated
     */
    private String aName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active.a_title
     *
     * @mbggenerated
     */
    private String aTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active.a_detail
     *
     * @mbggenerated
     */
    private String aDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active.a_pic
     *
     * @mbggenerated
     */
    private String aPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column active.a_temp
     *
     * @mbggenerated
     */
    private String aTemp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active.a_id
     *
     * @return the value of active.a_id
     *
     * @mbggenerated
     */
    public Integer getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active.a_id
     *
     * @param aId the value for active.a_id
     *
     * @mbggenerated
     */
    public void setaId(Integer aId) {
        this.aId = aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active.c_id
     *
     * @return the value of active.c_id
     *
     * @mbggenerated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active.c_id
     *
     * @param cId the value for active.c_id
     *
     * @mbggenerated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active.a_name
     *
     * @return the value of active.a_name
     *
     * @mbggenerated
     */
    public String getaName() {
        return aName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active.a_name
     *
     * @param aName the value for active.a_name
     *
     * @mbggenerated
     */
    public void setaName(String aName) {
        this.aName = aName == null ? null : aName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active.a_title
     *
     * @return the value of active.a_title
     *
     * @mbggenerated
     */
    public String getaTitle() {
        return aTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active.a_title
     *
     * @param aTitle the value for active.a_title
     *
     * @mbggenerated
     */
    public void setaTitle(String aTitle) {
        this.aTitle = aTitle == null ? null : aTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active.a_detail
     *
     * @return the value of active.a_detail
     *
     * @mbggenerated
     */
    public String getaDetail() {
        return aDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active.a_detail
     *
     * @param aDetail the value for active.a_detail
     *
     * @mbggenerated
     */
    public void setaDetail(String aDetail) {
        this.aDetail = aDetail == null ? null : aDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active.a_pic
     *
     * @return the value of active.a_pic
     *
     * @mbggenerated
     */
    public String getaPic() {
        return aPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active.a_pic
     *
     * @param aPic the value for active.a_pic
     *
     * @mbggenerated
     */
    public void setaPic(String aPic) {
        this.aPic = aPic == null ? null : aPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column active.a_temp
     *
     * @return the value of active.a_temp
     *
     * @mbggenerated
     */
    public String getaTemp() {
        return aTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column active.a_temp
     *
     * @param aTemp the value for active.a_temp
     *
     * @mbggenerated
     */
    public void setaTemp(String aTemp) {
        this.aTemp = aTemp == null ? null : aTemp.trim();
    }
}