package com.ll.po;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_id
     *
     * @mbggenerated
     */
    private Integer aId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_name
     *
     * @mbggenerated
     */
    private String aName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_pwd
     *
     * @mbggenerated
     */
    private String aPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_tel
     *
     * @mbggenerated
     */
    private String aTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_temp
     *
     * @mbggenerated
     */
    private String aTemp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_id
     *
     * @return the value of admin.a_id
     *
     * @mbggenerated
     */
    public Integer getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_id
     *
     * @param aId the value for admin.a_id
     *
     * @mbggenerated
     */
    public void setaId(Integer aId) {
        this.aId = aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_name
     *
     * @return the value of admin.a_name
     *
     * @mbggenerated
     */
    public String getaName() {
        return aName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_name
     *
     * @param aName the value for admin.a_name
     *
     * @mbggenerated
     */
    public void setaName(String aName) {
        this.aName = aName == null ? null : aName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_pwd
     *
     * @return the value of admin.a_pwd
     *
     * @mbggenerated
     */
    public String getaPwd() {
        return aPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_pwd
     *
     * @param aPwd the value for admin.a_pwd
     *
     * @mbggenerated
     */
    public void setaPwd(String aPwd) {
        this.aPwd = aPwd == null ? null : aPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_tel
     *
     * @return the value of admin.a_tel
     *
     * @mbggenerated
     */
    public String getaTel() {
        return aTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_tel
     *
     * @param aTel the value for admin.a_tel
     *
     * @mbggenerated
     */
    public void setaTel(String aTel) {
        this.aTel = aTel == null ? null : aTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_temp
     *
     * @return the value of admin.a_temp
     *
     * @mbggenerated
     */
    public String getaTemp() {
        return aTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_temp
     *
     * @param aTemp the value for admin.a_temp
     *
     * @mbggenerated
     */
    public void setaTemp(String aTemp) {
        this.aTemp = aTemp == null ? null : aTemp.trim();
    }
}