package com.ll.po;

import java.util.ArrayList;
import java.util.List;

public class CinemaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cinema
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cinema
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cinema
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema
     *
     * @mbggenerated
     */
    public CinemaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cinema
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCIdIsNull() {
            addCriterion("c_id is null");
            return (Criteria) this;
        }

        public Criteria andCIdIsNotNull() {
            addCriterion("c_id is not null");
            return (Criteria) this;
        }

        public Criteria andCIdEqualTo(Integer value) {
            addCriterion("c_id =", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdNotEqualTo(Integer value) {
            addCriterion("c_id <>", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdGreaterThan(Integer value) {
            addCriterion("c_id >", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("c_id >=", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdLessThan(Integer value) {
            addCriterion("c_id <", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdLessThanOrEqualTo(Integer value) {
            addCriterion("c_id <=", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdIn(List<Integer> values) {
            addCriterion("c_id in", values, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdNotIn(List<Integer> values) {
            addCriterion("c_id not in", values, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdBetween(Integer value1, Integer value2) {
            addCriterion("c_id between", value1, value2, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdNotBetween(Integer value1, Integer value2) {
            addCriterion("c_id not between", value1, value2, "cId");
            return (Criteria) this;
        }

        public Criteria andCNameIsNull() {
            addCriterion("c_name is null");
            return (Criteria) this;
        }

        public Criteria andCNameIsNotNull() {
            addCriterion("c_name is not null");
            return (Criteria) this;
        }

        public Criteria andCNameEqualTo(String value) {
            addCriterion("c_name =", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotEqualTo(String value) {
            addCriterion("c_name <>", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameGreaterThan(String value) {
            addCriterion("c_name >", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameGreaterThanOrEqualTo(String value) {
            addCriterion("c_name >=", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameLessThan(String value) {
            addCriterion("c_name <", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameLessThanOrEqualTo(String value) {
            addCriterion("c_name <=", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameLike(String value) {
            addCriterion("c_name like", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotLike(String value) {
            addCriterion("c_name not like", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameIn(List<String> values) {
            addCriterion("c_name in", values, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotIn(List<String> values) {
            addCriterion("c_name not in", values, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameBetween(String value1, String value2) {
            addCriterion("c_name between", value1, value2, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotBetween(String value1, String value2) {
            addCriterion("c_name not between", value1, value2, "cName");
            return (Criteria) this;
        }

        public Criteria andCTelIsNull() {
            addCriterion("c_tel is null");
            return (Criteria) this;
        }

        public Criteria andCTelIsNotNull() {
            addCriterion("c_tel is not null");
            return (Criteria) this;
        }

        public Criteria andCTelEqualTo(String value) {
            addCriterion("c_tel =", value, "cTel");
            return (Criteria) this;
        }

        public Criteria andCTelNotEqualTo(String value) {
            addCriterion("c_tel <>", value, "cTel");
            return (Criteria) this;
        }

        public Criteria andCTelGreaterThan(String value) {
            addCriterion("c_tel >", value, "cTel");
            return (Criteria) this;
        }

        public Criteria andCTelGreaterThanOrEqualTo(String value) {
            addCriterion("c_tel >=", value, "cTel");
            return (Criteria) this;
        }

        public Criteria andCTelLessThan(String value) {
            addCriterion("c_tel <", value, "cTel");
            return (Criteria) this;
        }

        public Criteria andCTelLessThanOrEqualTo(String value) {
            addCriterion("c_tel <=", value, "cTel");
            return (Criteria) this;
        }

        public Criteria andCTelLike(String value) {
            addCriterion("c_tel like", value, "cTel");
            return (Criteria) this;
        }

        public Criteria andCTelNotLike(String value) {
            addCriterion("c_tel not like", value, "cTel");
            return (Criteria) this;
        }

        public Criteria andCTelIn(List<String> values) {
            addCriterion("c_tel in", values, "cTel");
            return (Criteria) this;
        }

        public Criteria andCTelNotIn(List<String> values) {
            addCriterion("c_tel not in", values, "cTel");
            return (Criteria) this;
        }

        public Criteria andCTelBetween(String value1, String value2) {
            addCriterion("c_tel between", value1, value2, "cTel");
            return (Criteria) this;
        }

        public Criteria andCTelNotBetween(String value1, String value2) {
            addCriterion("c_tel not between", value1, value2, "cTel");
            return (Criteria) this;
        }

        public Criteria andCAddrIsNull() {
            addCriterion("c_addr is null");
            return (Criteria) this;
        }

        public Criteria andCAddrIsNotNull() {
            addCriterion("c_addr is not null");
            return (Criteria) this;
        }

        public Criteria andCAddrEqualTo(String value) {
            addCriterion("c_addr =", value, "cAddr");
            return (Criteria) this;
        }

        public Criteria andCAddrNotEqualTo(String value) {
            addCriterion("c_addr <>", value, "cAddr");
            return (Criteria) this;
        }

        public Criteria andCAddrGreaterThan(String value) {
            addCriterion("c_addr >", value, "cAddr");
            return (Criteria) this;
        }

        public Criteria andCAddrGreaterThanOrEqualTo(String value) {
            addCriterion("c_addr >=", value, "cAddr");
            return (Criteria) this;
        }

        public Criteria andCAddrLessThan(String value) {
            addCriterion("c_addr <", value, "cAddr");
            return (Criteria) this;
        }

        public Criteria andCAddrLessThanOrEqualTo(String value) {
            addCriterion("c_addr <=", value, "cAddr");
            return (Criteria) this;
        }

        public Criteria andCAddrLike(String value) {
            addCriterion("c_addr like", value, "cAddr");
            return (Criteria) this;
        }

        public Criteria andCAddrNotLike(String value) {
            addCriterion("c_addr not like", value, "cAddr");
            return (Criteria) this;
        }

        public Criteria andCAddrIn(List<String> values) {
            addCriterion("c_addr in", values, "cAddr");
            return (Criteria) this;
        }

        public Criteria andCAddrNotIn(List<String> values) {
            addCriterion("c_addr not in", values, "cAddr");
            return (Criteria) this;
        }

        public Criteria andCAddrBetween(String value1, String value2) {
            addCriterion("c_addr between", value1, value2, "cAddr");
            return (Criteria) this;
        }

        public Criteria andCAddrNotBetween(String value1, String value2) {
            addCriterion("c_addr not between", value1, value2, "cAddr");
            return (Criteria) this;
        }

        public Criteria andCServeIsNull() {
            addCriterion("c_serve is null");
            return (Criteria) this;
        }

        public Criteria andCServeIsNotNull() {
            addCriterion("c_serve is not null");
            return (Criteria) this;
        }

        public Criteria andCServeEqualTo(String value) {
            addCriterion("c_serve =", value, "cServe");
            return (Criteria) this;
        }

        public Criteria andCServeNotEqualTo(String value) {
            addCriterion("c_serve <>", value, "cServe");
            return (Criteria) this;
        }

        public Criteria andCServeGreaterThan(String value) {
            addCriterion("c_serve >", value, "cServe");
            return (Criteria) this;
        }

        public Criteria andCServeGreaterThanOrEqualTo(String value) {
            addCriterion("c_serve >=", value, "cServe");
            return (Criteria) this;
        }

        public Criteria andCServeLessThan(String value) {
            addCriterion("c_serve <", value, "cServe");
            return (Criteria) this;
        }

        public Criteria andCServeLessThanOrEqualTo(String value) {
            addCriterion("c_serve <=", value, "cServe");
            return (Criteria) this;
        }

        public Criteria andCServeLike(String value) {
            addCriterion("c_serve like", value, "cServe");
            return (Criteria) this;
        }

        public Criteria andCServeNotLike(String value) {
            addCriterion("c_serve not like", value, "cServe");
            return (Criteria) this;
        }

        public Criteria andCServeIn(List<String> values) {
            addCriterion("c_serve in", values, "cServe");
            return (Criteria) this;
        }

        public Criteria andCServeNotIn(List<String> values) {
            addCriterion("c_serve not in", values, "cServe");
            return (Criteria) this;
        }

        public Criteria andCServeBetween(String value1, String value2) {
            addCriterion("c_serve between", value1, value2, "cServe");
            return (Criteria) this;
        }

        public Criteria andCServeNotBetween(String value1, String value2) {
            addCriterion("c_serve not between", value1, value2, "cServe");
            return (Criteria) this;
        }

        public Criteria andCPicIsNull() {
            addCriterion("c_pic is null");
            return (Criteria) this;
        }

        public Criteria andCPicIsNotNull() {
            addCriterion("c_pic is not null");
            return (Criteria) this;
        }

        public Criteria andCPicEqualTo(String value) {
            addCriterion("c_pic =", value, "cPic");
            return (Criteria) this;
        }

        public Criteria andCPicNotEqualTo(String value) {
            addCriterion("c_pic <>", value, "cPic");
            return (Criteria) this;
        }

        public Criteria andCPicGreaterThan(String value) {
            addCriterion("c_pic >", value, "cPic");
            return (Criteria) this;
        }

        public Criteria andCPicGreaterThanOrEqualTo(String value) {
            addCriterion("c_pic >=", value, "cPic");
            return (Criteria) this;
        }

        public Criteria andCPicLessThan(String value) {
            addCriterion("c_pic <", value, "cPic");
            return (Criteria) this;
        }

        public Criteria andCPicLessThanOrEqualTo(String value) {
            addCriterion("c_pic <=", value, "cPic");
            return (Criteria) this;
        }

        public Criteria andCPicLike(String value) {
            addCriterion("c_pic like", value, "cPic");
            return (Criteria) this;
        }

        public Criteria andCPicNotLike(String value) {
            addCriterion("c_pic not like", value, "cPic");
            return (Criteria) this;
        }

        public Criteria andCPicIn(List<String> values) {
            addCriterion("c_pic in", values, "cPic");
            return (Criteria) this;
        }

        public Criteria andCPicNotIn(List<String> values) {
            addCriterion("c_pic not in", values, "cPic");
            return (Criteria) this;
        }

        public Criteria andCPicBetween(String value1, String value2) {
            addCriterion("c_pic between", value1, value2, "cPic");
            return (Criteria) this;
        }

        public Criteria andCPicNotBetween(String value1, String value2) {
            addCriterion("c_pic not between", value1, value2, "cPic");
            return (Criteria) this;
        }

        public Criteria andCTempIsNull() {
            addCriterion("c_temp is null");
            return (Criteria) this;
        }

        public Criteria andCTempIsNotNull() {
            addCriterion("c_temp is not null");
            return (Criteria) this;
        }

        public Criteria andCTempEqualTo(String value) {
            addCriterion("c_temp =", value, "cTemp");
            return (Criteria) this;
        }

        public Criteria andCTempNotEqualTo(String value) {
            addCriterion("c_temp <>", value, "cTemp");
            return (Criteria) this;
        }

        public Criteria andCTempGreaterThan(String value) {
            addCriterion("c_temp >", value, "cTemp");
            return (Criteria) this;
        }

        public Criteria andCTempGreaterThanOrEqualTo(String value) {
            addCriterion("c_temp >=", value, "cTemp");
            return (Criteria) this;
        }

        public Criteria andCTempLessThan(String value) {
            addCriterion("c_temp <", value, "cTemp");
            return (Criteria) this;
        }

        public Criteria andCTempLessThanOrEqualTo(String value) {
            addCriterion("c_temp <=", value, "cTemp");
            return (Criteria) this;
        }

        public Criteria andCTempLike(String value) {
            addCriterion("c_temp like", value, "cTemp");
            return (Criteria) this;
        }

        public Criteria andCTempNotLike(String value) {
            addCriterion("c_temp not like", value, "cTemp");
            return (Criteria) this;
        }

        public Criteria andCTempIn(List<String> values) {
            addCriterion("c_temp in", values, "cTemp");
            return (Criteria) this;
        }

        public Criteria andCTempNotIn(List<String> values) {
            addCriterion("c_temp not in", values, "cTemp");
            return (Criteria) this;
        }

        public Criteria andCTempBetween(String value1, String value2) {
            addCriterion("c_temp between", value1, value2, "cTemp");
            return (Criteria) this;
        }

        public Criteria andCTempNotBetween(String value1, String value2) {
            addCriterion("c_temp not between", value1, value2, "cTemp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cinema
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cinema
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}