package com.ll.po;

public class Cinema {
	
    @Override
	public String toString() {
		return "Cinema [cId=" + cId + ", cName=" + cName + ", cTel=" + cTel + ", cAddr=" + cAddr + ", cServe=" + cServe
				+ ", cPic=" + cPic + ", cTemp=" + cTemp + "]";
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema.c_id
     *
     * @mbggenerated
     */
    private Integer cId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema.c_name
     *
     * @mbggenerated
     */
    private String cName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema.c_tel
     *
     * @mbggenerated
     */
    private String cTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema.c_addr
     *
     * @mbggenerated
     */
    private String cAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema.c_serve
     *
     * @mbggenerated
     */
    private String cServe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema.c_pic
     *
     * @mbggenerated
     */
    private String cPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cinema.c_temp
     *
     * @mbggenerated
     */
    private String cTemp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema.c_id
     *
     * @return the value of cinema.c_id
     *
     * @mbggenerated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema.c_id
     *
     * @param cId the value for cinema.c_id
     *
     * @mbggenerated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema.c_name
     *
     * @return the value of cinema.c_name
     *
     * @mbggenerated
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema.c_name
     *
     * @param cName the value for cinema.c_name
     *
     * @mbggenerated
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema.c_tel
     *
     * @return the value of cinema.c_tel
     *
     * @mbggenerated
     */
    public String getcTel() {
        return cTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema.c_tel
     *
     * @param cTel the value for cinema.c_tel
     *
     * @mbggenerated
     */
    public void setcTel(String cTel) {
        this.cTel = cTel == null ? null : cTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema.c_addr
     *
     * @return the value of cinema.c_addr
     *
     * @mbggenerated
     */
    public String getcAddr() {
        return cAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema.c_addr
     *
     * @param cAddr the value for cinema.c_addr
     *
     * @mbggenerated
     */
    public void setcAddr(String cAddr) {
        this.cAddr = cAddr == null ? null : cAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema.c_serve
     *
     * @return the value of cinema.c_serve
     *
     * @mbggenerated
     */
    public String getcServe() {
        return cServe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema.c_serve
     *
     * @param cServe the value for cinema.c_serve
     *
     * @mbggenerated
     */
    public void setcServe(String cServe) {
        this.cServe = cServe == null ? null : cServe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema.c_pic
     *
     * @return the value of cinema.c_pic
     *
     * @mbggenerated
     */
    public String getcPic() {
        return cPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema.c_pic
     *
     * @param cPic the value for cinema.c_pic
     *
     * @mbggenerated
     */
    public void setcPic(String cPic) {
        this.cPic = cPic == null ? null : cPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cinema.c_temp
     *
     * @return the value of cinema.c_temp
     *
     * @mbggenerated
     */
    public String getcTemp() {
        return cTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cinema.c_temp
     *
     * @param cTemp the value for cinema.c_temp
     *
     * @mbggenerated
     */
    public void setcTemp(String cTemp) {
        this.cTemp = cTemp == null ? null : cTemp.trim();
    }
}