package com.ll.po;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.co_id
     *
     * @mbggenerated
     */
    private Integer coId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.co_cord
     *
     * @mbggenerated
     */
    private Double coCord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.u_id
     *
     * @mbggenerated
     */
    private Integer uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.f_id
     *
     * @mbggenerated
     */
    private Integer fId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.co_content
     *
     * @mbggenerated
     */
    private String coContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.co_temp
     *
     * @mbggenerated
     */
    private String coTemp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.co_id
     *
     * @return the value of comment.co_id
     *
     * @mbggenerated
     */
    public Integer getCoId() {
        return coId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.co_id
     *
     * @param coId the value for comment.co_id
     *
     * @mbggenerated
     */
    public void setCoId(Integer coId) {
        this.coId = coId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.co_cord
     *
     * @return the value of comment.co_cord
     *
     * @mbggenerated
     */
    public Double getCoCord() {
        return coCord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.co_cord
     *
     * @param coCord the value for comment.co_cord
     *
     * @mbggenerated
     */
    public void setCoCord(Double coCord) {
        this.coCord = coCord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.u_id
     *
     * @return the value of comment.u_id
     *
     * @mbggenerated
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.u_id
     *
     * @param uId the value for comment.u_id
     *
     * @mbggenerated
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.f_id
     *
     * @return the value of comment.f_id
     *
     * @mbggenerated
     */
    public Integer getfId() {
        return fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.f_id
     *
     * @param fId the value for comment.f_id
     *
     * @mbggenerated
     */
    public void setfId(Integer fId) {
        this.fId = fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.co_content
     *
     * @return the value of comment.co_content
     *
     * @mbggenerated
     */
    public String getCoContent() {
        return coContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.co_content
     *
     * @param coContent the value for comment.co_content
     *
     * @mbggenerated
     */
    public void setCoContent(String coContent) {
        this.coContent = coContent == null ? null : coContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.co_temp
     *
     * @return the value of comment.co_temp
     *
     * @mbggenerated
     */
    public String getCoTemp() {
        return coTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.co_temp
     *
     * @param coTemp the value for comment.co_temp
     *
     * @mbggenerated
     */
    public void setCoTemp(String coTemp) {
        this.coTemp = coTemp == null ? null : coTemp.trim();
    }
}