package com.ll.po;

import java.util.Date;

public class Film {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.f_id
     *
     * @mbggenerated
     */
    private Integer fId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.f_name
     *
     * @mbggenerated
     */
    private String fName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.f_director
     *
     * @mbggenerated
     */
    private String fDirector;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.f_actor
     *
     * @mbggenerated
     */
    private String fActor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.f_pdate
     *
     * @mbggenerated
     */
    private Date fPdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.f_cord
     *
     * @mbggenerated
     */
    private Double fCord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.f_type
     *
     * @mbggenerated
     */
    private String fType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.f_time
     *
     * @mbggenerated
     */
    private String fTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.f_pic
     *
     * @mbggenerated
     */
    private String fPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.f_video
     *
     * @mbggenerated
     */
    private String fVideo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.f_status
     *
     * @mbggenerated
     */
    private Integer fStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.f_desc
     *
     * @mbggenerated
     */
    private String fDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column film.f_temp
     *
     * @mbggenerated
     */
    private String fTemp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.f_id
     *
     * @return the value of film.f_id
     *
     * @mbggenerated
     */
    public Integer getfId() {
        return fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.f_id
     *
     * @param fId the value for film.f_id
     *
     * @mbggenerated
     */
    public void setfId(Integer fId) {
        this.fId = fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.f_name
     *
     * @return the value of film.f_name
     *
     * @mbggenerated
     */
    public String getfName() {
        return fName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.f_name
     *
     * @param fName the value for film.f_name
     *
     * @mbggenerated
     */
    public void setfName(String fName) {
        this.fName = fName == null ? null : fName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.f_director
     *
     * @return the value of film.f_director
     *
     * @mbggenerated
     */
    public String getfDirector() {
        return fDirector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.f_director
     *
     * @param fDirector the value for film.f_director
     *
     * @mbggenerated
     */
    public void setfDirector(String fDirector) {
        this.fDirector = fDirector == null ? null : fDirector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.f_actor
     *
     * @return the value of film.f_actor
     *
     * @mbggenerated
     */
    public String getfActor() {
        return fActor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.f_actor
     *
     * @param fActor the value for film.f_actor
     *
     * @mbggenerated
     */
    public void setfActor(String fActor) {
        this.fActor = fActor == null ? null : fActor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.f_pdate
     *
     * @return the value of film.f_pdate
     *
     * @mbggenerated
     */
    public Date getfPdate() {
        return fPdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.f_pdate
     *
     * @param fPdate the value for film.f_pdate
     *
     * @mbggenerated
     */
    public void setfPdate(Date fPdate) {
        this.fPdate = fPdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.f_cord
     *
     * @return the value of film.f_cord
     *
     * @mbggenerated
     */
    public Double getfCord() {
        return fCord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.f_cord
     *
     * @param fCord the value for film.f_cord
     *
     * @mbggenerated
     */
    public void setfCord(Double fCord) {
        this.fCord = fCord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.f_type
     *
     * @return the value of film.f_type
     *
     * @mbggenerated
     */
    public String getfType() {
        return fType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.f_type
     *
     * @param fType the value for film.f_type
     *
     * @mbggenerated
     */
    public void setfType(String fType) {
        this.fType = fType == null ? null : fType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.f_time
     *
     * @return the value of film.f_time
     *
     * @mbggenerated
     */
    public String getfTime() {
        return fTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.f_time
     *
     * @param fTime the value for film.f_time
     *
     * @mbggenerated
     */
    public void setfTime(String fTime) {
        this.fTime = fTime == null ? null : fTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.f_pic
     *
     * @return the value of film.f_pic
     *
     * @mbggenerated
     */
    public String getfPic() {
        return fPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.f_pic
     *
     * @param fPic the value for film.f_pic
     *
     * @mbggenerated
     */
    public void setfPic(String fPic) {
        this.fPic = fPic == null ? null : fPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.f_video
     *
     * @return the value of film.f_video
     *
     * @mbggenerated
     */
    public String getfVideo() {
        return fVideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.f_video
     *
     * @param fVideo the value for film.f_video
     *
     * @mbggenerated
     */
    public void setfVideo(String fVideo) {
        this.fVideo = fVideo == null ? null : fVideo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.f_status
     *
     * @return the value of film.f_status
     *
     * @mbggenerated
     */
    public Integer getfStatus() {
        return fStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.f_status
     *
     * @param fStatus the value for film.f_status
     *
     * @mbggenerated
     */
    public void setfStatus(Integer fStatus) {
        this.fStatus = fStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.f_desc
     *
     * @return the value of film.f_desc
     *
     * @mbggenerated
     */
    public String getfDesc() {
        return fDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.f_desc
     *
     * @param fDesc the value for film.f_desc
     *
     * @mbggenerated
     */
    public void setfDesc(String fDesc) {
        this.fDesc = fDesc == null ? null : fDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column film.f_temp
     *
     * @return the value of film.f_temp
     *
     * @mbggenerated
     */
    public String getfTemp() {
        return fTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column film.f_temp
     *
     * @param fTemp the value for film.f_temp
     *
     * @mbggenerated
     */
    public void setfTemp(String fTemp) {
        this.fTemp = fTemp == null ? null : fTemp.trim();
    }
}