package com.ll.po;

public class Hall {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hall.h_id
     *
     * @mbggenerated
     */
    private Integer hId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hall.c_id
     *
     * @mbggenerated
     */
    private Integer cId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hall.h_type
     *
     * @mbggenerated
     */
    private String hType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hall.h_desc
     *
     * @mbggenerated
     */
    private String hDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hall.h_size
     *
     * @mbggenerated
     */
    private String hSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hall.h_status
     *
     * @mbggenerated
     */
    private Integer hStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hall.h_temp
     *
     * @mbggenerated
     */
    private String hTemp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hall.h_id
     *
     * @return the value of hall.h_id
     *
     * @mbggenerated
     */
    public Integer gethId() {
        return hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hall.h_id
     *
     * @param hId the value for hall.h_id
     *
     * @mbggenerated
     */
    public void sethId(Integer hId) {
        this.hId = hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hall.c_id
     *
     * @return the value of hall.c_id
     *
     * @mbggenerated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hall.c_id
     *
     * @param cId the value for hall.c_id
     *
     * @mbggenerated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hall.h_type
     *
     * @return the value of hall.h_type
     *
     * @mbggenerated
     */
    public String gethType() {
        return hType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hall.h_type
     *
     * @param hType the value for hall.h_type
     *
     * @mbggenerated
     */
    public void sethType(String hType) {
        this.hType = hType == null ? null : hType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hall.h_desc
     *
     * @return the value of hall.h_desc
     *
     * @mbggenerated
     */
    public String gethDesc() {
        return hDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hall.h_desc
     *
     * @param hDesc the value for hall.h_desc
     *
     * @mbggenerated
     */
    public void sethDesc(String hDesc) {
        this.hDesc = hDesc == null ? null : hDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hall.h_size
     *
     * @return the value of hall.h_size
     *
     * @mbggenerated
     */
    public String gethSize() {
        return hSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hall.h_size
     *
     * @param hSize the value for hall.h_size
     *
     * @mbggenerated
     */
    public void sethSize(String hSize) {
        this.hSize = hSize == null ? null : hSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hall.h_status
     *
     * @return the value of hall.h_status
     *
     * @mbggenerated
     */
    public Integer gethStatus() {
        return hStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hall.h_status
     *
     * @param hStatus the value for hall.h_status
     *
     * @mbggenerated
     */
    public void sethStatus(Integer hStatus) {
        this.hStatus = hStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hall.h_temp
     *
     * @return the value of hall.h_temp
     *
     * @mbggenerated
     */
    public String gethTemp() {
        return hTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hall.h_temp
     *
     * @param hTemp the value for hall.h_temp
     *
     * @mbggenerated
     */
    public void sethTemp(String hTemp) {
        this.hTemp = hTemp == null ? null : hTemp.trim();
    }
}