package com.ll.po;

import java.util.Date;

public class Member {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.m_id
     *
     * @mbggenerated
     */
    private Integer mId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.m_sdate
     *
     * @mbggenerated
     */
    private Date mSdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.m_edate
     *
     * @mbggenerated
     */
    private Date mEdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.m_status
     *
     * @mbggenerated
     */
    private Integer mStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.m_temp
     *
     * @mbggenerated
     */
    private String mTemp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.m_id
     *
     * @return the value of member.m_id
     *
     * @mbggenerated
     */
    public Integer getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.m_id
     *
     * @param mId the value for member.m_id
     *
     * @mbggenerated
     */
    public void setmId(Integer mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.m_sdate
     *
     * @return the value of member.m_sdate
     *
     * @mbggenerated
     */
    public Date getmSdate() {
        return mSdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.m_sdate
     *
     * @param mSdate the value for member.m_sdate
     *
     * @mbggenerated
     */
    public void setmSdate(Date mSdate) {
        this.mSdate = mSdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.m_edate
     *
     * @return the value of member.m_edate
     *
     * @mbggenerated
     */
    public Date getmEdate() {
        return mEdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.m_edate
     *
     * @param mEdate the value for member.m_edate
     *
     * @mbggenerated
     */
    public void setmEdate(Date mEdate) {
        this.mEdate = mEdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.m_status
     *
     * @return the value of member.m_status
     *
     * @mbggenerated
     */
    public Integer getmStatus() {
        return mStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.m_status
     *
     * @param mStatus the value for member.m_status
     *
     * @mbggenerated
     */
    public void setmStatus(Integer mStatus) {
        this.mStatus = mStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.m_temp
     *
     * @return the value of member.m_temp
     *
     * @mbggenerated
     */
    public String getmTemp() {
        return mTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.m_temp
     *
     * @param mTemp the value for member.m_temp
     *
     * @mbggenerated
     */
    public void setmTemp(String mTemp) {
        this.mTemp = mTemp == null ? null : mTemp.trim();
    }
}