package com.ll.po;

import java.util.Date;

public class Orderitem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.oi_id
     *
     * @mbggenerated
     */
    private Integer oiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.o_id
     *
     * @mbggenerated
     */
    private Integer oId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.f_id
     *
     * @mbggenerated
     */
    private Integer fId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.s_id
     *
     * @mbggenerated
     */
    private Integer sId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.c_name
     *
     * @mbggenerated
     */
    private String cName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.oi_price
     *
     * @mbggenerated
     */
    private Double oiPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.oi_date
     *
     * @mbggenerated
     */
    private Date oiDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.oi_seat
     *
     * @mbggenerated
     */
    private String oiSeat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.oi_time
     *
     * @mbggenerated
     */
    private String oiTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.oi_temp
     *
     * @mbggenerated
     */
    private String oiTemp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.oi_id
     *
     * @return the value of orderitem.oi_id
     *
     * @mbggenerated
     */
    public Integer getOiId() {
        return oiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.oi_id
     *
     * @param oiId the value for orderitem.oi_id
     *
     * @mbggenerated
     */
    public void setOiId(Integer oiId) {
        this.oiId = oiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.o_id
     *
     * @return the value of orderitem.o_id
     *
     * @mbggenerated
     */
    public Integer getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.o_id
     *
     * @param oId the value for orderitem.o_id
     *
     * @mbggenerated
     */
    public void setoId(Integer oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.f_id
     *
     * @return the value of orderitem.f_id
     *
     * @mbggenerated
     */
    public Integer getfId() {
        return fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.f_id
     *
     * @param fId the value for orderitem.f_id
     *
     * @mbggenerated
     */
    public void setfId(Integer fId) {
        this.fId = fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.s_id
     *
     * @return the value of orderitem.s_id
     *
     * @mbggenerated
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.s_id
     *
     * @param sId the value for orderitem.s_id
     *
     * @mbggenerated
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.c_name
     *
     * @return the value of orderitem.c_name
     *
     * @mbggenerated
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.c_name
     *
     * @param cName the value for orderitem.c_name
     *
     * @mbggenerated
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.oi_price
     *
     * @return the value of orderitem.oi_price
     *
     * @mbggenerated
     */
    public Double getOiPrice() {
        return oiPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.oi_price
     *
     * @param oiPrice the value for orderitem.oi_price
     *
     * @mbggenerated
     */
    public void setOiPrice(Double oiPrice) {
        this.oiPrice = oiPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.oi_date
     *
     * @return the value of orderitem.oi_date
     *
     * @mbggenerated
     */
    public Date getOiDate() {
        return oiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.oi_date
     *
     * @param oiDate the value for orderitem.oi_date
     *
     * @mbggenerated
     */
    public void setOiDate(Date oiDate) {
        this.oiDate = oiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.oi_seat
     *
     * @return the value of orderitem.oi_seat
     *
     * @mbggenerated
     */
    public String getOiSeat() {
        return oiSeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.oi_seat
     *
     * @param oiSeat the value for orderitem.oi_seat
     *
     * @mbggenerated
     */
    public void setOiSeat(String oiSeat) {
        this.oiSeat = oiSeat == null ? null : oiSeat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.oi_time
     *
     * @return the value of orderitem.oi_time
     *
     * @mbggenerated
     */
    public String getOiTime() {
        return oiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.oi_time
     *
     * @param oiTime the value for orderitem.oi_time
     *
     * @mbggenerated
     */
    public void setOiTime(String oiTime) {
        this.oiTime = oiTime == null ? null : oiTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.oi_temp
     *
     * @return the value of orderitem.oi_temp
     *
     * @mbggenerated
     */
    public String getOiTemp() {
        return oiTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.oi_temp
     *
     * @param oiTemp the value for orderitem.oi_temp
     *
     * @mbggenerated
     */
    public void setOiTemp(String oiTemp) {
        this.oiTemp = oiTemp == null ? null : oiTemp.trim();
    }
}