package com.ll.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    public OrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOIdIsNull() {
            addCriterion("o_id is null");
            return (Criteria) this;
        }

        public Criteria andOIdIsNotNull() {
            addCriterion("o_id is not null");
            return (Criteria) this;
        }

        public Criteria andOIdEqualTo(Integer value) {
            addCriterion("o_id =", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotEqualTo(Integer value) {
            addCriterion("o_id <>", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdGreaterThan(Integer value) {
            addCriterion("o_id >", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("o_id >=", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdLessThan(Integer value) {
            addCriterion("o_id <", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdLessThanOrEqualTo(Integer value) {
            addCriterion("o_id <=", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdIn(List<Integer> values) {
            addCriterion("o_id in", values, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotIn(List<Integer> values) {
            addCriterion("o_id not in", values, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdBetween(Integer value1, Integer value2) {
            addCriterion("o_id between", value1, value2, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotBetween(Integer value1, Integer value2) {
            addCriterion("o_id not between", value1, value2, "oId");
            return (Criteria) this;
        }

        public Criteria andUIdIsNull() {
            addCriterion("u_id is null");
            return (Criteria) this;
        }

        public Criteria andUIdIsNotNull() {
            addCriterion("u_id is not null");
            return (Criteria) this;
        }

        public Criteria andUIdEqualTo(Integer value) {
            addCriterion("u_id =", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotEqualTo(Integer value) {
            addCriterion("u_id <>", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdGreaterThan(Integer value) {
            addCriterion("u_id >", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("u_id >=", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdLessThan(Integer value) {
            addCriterion("u_id <", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdLessThanOrEqualTo(Integer value) {
            addCriterion("u_id <=", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdIn(List<Integer> values) {
            addCriterion("u_id in", values, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotIn(List<Integer> values) {
            addCriterion("u_id not in", values, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdBetween(Integer value1, Integer value2) {
            addCriterion("u_id between", value1, value2, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotBetween(Integer value1, Integer value2) {
            addCriterion("u_id not between", value1, value2, "uId");
            return (Criteria) this;
        }

        public Criteria andSIdIsNull() {
            addCriterion("s_id is null");
            return (Criteria) this;
        }

        public Criteria andSIdIsNotNull() {
            addCriterion("s_id is not null");
            return (Criteria) this;
        }

        public Criteria andSIdEqualTo(Integer value) {
            addCriterion("s_id =", value, "sId");
            return (Criteria) this;
        }

        public Criteria andSIdNotEqualTo(Integer value) {
            addCriterion("s_id <>", value, "sId");
            return (Criteria) this;
        }

        public Criteria andSIdGreaterThan(Integer value) {
            addCriterion("s_id >", value, "sId");
            return (Criteria) this;
        }

        public Criteria andSIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("s_id >=", value, "sId");
            return (Criteria) this;
        }

        public Criteria andSIdLessThan(Integer value) {
            addCriterion("s_id <", value, "sId");
            return (Criteria) this;
        }

        public Criteria andSIdLessThanOrEqualTo(Integer value) {
            addCriterion("s_id <=", value, "sId");
            return (Criteria) this;
        }

        public Criteria andSIdIn(List<Integer> values) {
            addCriterion("s_id in", values, "sId");
            return (Criteria) this;
        }

        public Criteria andSIdNotIn(List<Integer> values) {
            addCriterion("s_id not in", values, "sId");
            return (Criteria) this;
        }

        public Criteria andSIdBetween(Integer value1, Integer value2) {
            addCriterion("s_id between", value1, value2, "sId");
            return (Criteria) this;
        }

        public Criteria andSIdNotBetween(Integer value1, Integer value2) {
            addCriterion("s_id not between", value1, value2, "sId");
            return (Criteria) this;
        }

        public Criteria andFIdIsNull() {
            addCriterion("f_id is null");
            return (Criteria) this;
        }

        public Criteria andFIdIsNotNull() {
            addCriterion("f_id is not null");
            return (Criteria) this;
        }

        public Criteria andFIdEqualTo(Integer value) {
            addCriterion("f_id =", value, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdNotEqualTo(Integer value) {
            addCriterion("f_id <>", value, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdGreaterThan(Integer value) {
            addCriterion("f_id >", value, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_id >=", value, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdLessThan(Integer value) {
            addCriterion("f_id <", value, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdLessThanOrEqualTo(Integer value) {
            addCriterion("f_id <=", value, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdIn(List<Integer> values) {
            addCriterion("f_id in", values, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdNotIn(List<Integer> values) {
            addCriterion("f_id not in", values, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdBetween(Integer value1, Integer value2) {
            addCriterion("f_id between", value1, value2, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdNotBetween(Integer value1, Integer value2) {
            addCriterion("f_id not between", value1, value2, "fId");
            return (Criteria) this;
        }

        public Criteria andONumIsNull() {
            addCriterion("o_num is null");
            return (Criteria) this;
        }

        public Criteria andONumIsNotNull() {
            addCriterion("o_num is not null");
            return (Criteria) this;
        }

        public Criteria andONumEqualTo(Integer value) {
            addCriterion("o_num =", value, "oNum");
            return (Criteria) this;
        }

        public Criteria andONumNotEqualTo(Integer value) {
            addCriterion("o_num <>", value, "oNum");
            return (Criteria) this;
        }

        public Criteria andONumGreaterThan(Integer value) {
            addCriterion("o_num >", value, "oNum");
            return (Criteria) this;
        }

        public Criteria andONumGreaterThanOrEqualTo(Integer value) {
            addCriterion("o_num >=", value, "oNum");
            return (Criteria) this;
        }

        public Criteria andONumLessThan(Integer value) {
            addCriterion("o_num <", value, "oNum");
            return (Criteria) this;
        }

        public Criteria andONumLessThanOrEqualTo(Integer value) {
            addCriterion("o_num <=", value, "oNum");
            return (Criteria) this;
        }

        public Criteria andONumIn(List<Integer> values) {
            addCriterion("o_num in", values, "oNum");
            return (Criteria) this;
        }

        public Criteria andONumNotIn(List<Integer> values) {
            addCriterion("o_num not in", values, "oNum");
            return (Criteria) this;
        }

        public Criteria andONumBetween(Integer value1, Integer value2) {
            addCriterion("o_num between", value1, value2, "oNum");
            return (Criteria) this;
        }

        public Criteria andONumNotBetween(Integer value1, Integer value2) {
            addCriterion("o_num not between", value1, value2, "oNum");
            return (Criteria) this;
        }

        public Criteria andOPriceIsNull() {
            addCriterion("o_price is null");
            return (Criteria) this;
        }

        public Criteria andOPriceIsNotNull() {
            addCriterion("o_price is not null");
            return (Criteria) this;
        }

        public Criteria andOPriceEqualTo(Double value) {
            addCriterion("o_price =", value, "oPrice");
            return (Criteria) this;
        }

        public Criteria andOPriceNotEqualTo(Double value) {
            addCriterion("o_price <>", value, "oPrice");
            return (Criteria) this;
        }

        public Criteria andOPriceGreaterThan(Double value) {
            addCriterion("o_price >", value, "oPrice");
            return (Criteria) this;
        }

        public Criteria andOPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("o_price >=", value, "oPrice");
            return (Criteria) this;
        }

        public Criteria andOPriceLessThan(Double value) {
            addCriterion("o_price <", value, "oPrice");
            return (Criteria) this;
        }

        public Criteria andOPriceLessThanOrEqualTo(Double value) {
            addCriterion("o_price <=", value, "oPrice");
            return (Criteria) this;
        }

        public Criteria andOPriceIn(List<Double> values) {
            addCriterion("o_price in", values, "oPrice");
            return (Criteria) this;
        }

        public Criteria andOPriceNotIn(List<Double> values) {
            addCriterion("o_price not in", values, "oPrice");
            return (Criteria) this;
        }

        public Criteria andOPriceBetween(Double value1, Double value2) {
            addCriterion("o_price between", value1, value2, "oPrice");
            return (Criteria) this;
        }

        public Criteria andOPriceNotBetween(Double value1, Double value2) {
            addCriterion("o_price not between", value1, value2, "oPrice");
            return (Criteria) this;
        }

        public Criteria andOSeatIsNull() {
            addCriterion("o_seat is null");
            return (Criteria) this;
        }

        public Criteria andOSeatIsNotNull() {
            addCriterion("o_seat is not null");
            return (Criteria) this;
        }

        public Criteria andOSeatEqualTo(String value) {
            addCriterion("o_seat =", value, "oSeat");
            return (Criteria) this;
        }

        public Criteria andOSeatNotEqualTo(String value) {
            addCriterion("o_seat <>", value, "oSeat");
            return (Criteria) this;
        }

        public Criteria andOSeatGreaterThan(String value) {
            addCriterion("o_seat >", value, "oSeat");
            return (Criteria) this;
        }

        public Criteria andOSeatGreaterThanOrEqualTo(String value) {
            addCriterion("o_seat >=", value, "oSeat");
            return (Criteria) this;
        }

        public Criteria andOSeatLessThan(String value) {
            addCriterion("o_seat <", value, "oSeat");
            return (Criteria) this;
        }

        public Criteria andOSeatLessThanOrEqualTo(String value) {
            addCriterion("o_seat <=", value, "oSeat");
            return (Criteria) this;
        }

        public Criteria andOSeatLike(String value) {
            addCriterion("o_seat like", value, "oSeat");
            return (Criteria) this;
        }

        public Criteria andOSeatNotLike(String value) {
            addCriterion("o_seat not like", value, "oSeat");
            return (Criteria) this;
        }

        public Criteria andOSeatIn(List<String> values) {
            addCriterion("o_seat in", values, "oSeat");
            return (Criteria) this;
        }

        public Criteria andOSeatNotIn(List<String> values) {
            addCriterion("o_seat not in", values, "oSeat");
            return (Criteria) this;
        }

        public Criteria andOSeatBetween(String value1, String value2) {
            addCriterion("o_seat between", value1, value2, "oSeat");
            return (Criteria) this;
        }

        public Criteria andOSeatNotBetween(String value1, String value2) {
            addCriterion("o_seat not between", value1, value2, "oSeat");
            return (Criteria) this;
        }

        public Criteria andOSdateIsNull() {
            addCriterion("o_sdate is null");
            return (Criteria) this;
        }

        public Criteria andOSdateIsNotNull() {
            addCriterion("o_sdate is not null");
            return (Criteria) this;
        }

        public Criteria andOSdateEqualTo(Date value) {
            addCriterion("o_sdate =", value, "oSdate");
            return (Criteria) this;
        }

        public Criteria andOSdateNotEqualTo(Date value) {
            addCriterion("o_sdate <>", value, "oSdate");
            return (Criteria) this;
        }

        public Criteria andOSdateGreaterThan(Date value) {
            addCriterion("o_sdate >", value, "oSdate");
            return (Criteria) this;
        }

        public Criteria andOSdateGreaterThanOrEqualTo(Date value) {
            addCriterion("o_sdate >=", value, "oSdate");
            return (Criteria) this;
        }

        public Criteria andOSdateLessThan(Date value) {
            addCriterion("o_sdate <", value, "oSdate");
            return (Criteria) this;
        }

        public Criteria andOSdateLessThanOrEqualTo(Date value) {
            addCriterion("o_sdate <=", value, "oSdate");
            return (Criteria) this;
        }

        public Criteria andOSdateIn(List<Date> values) {
            addCriterion("o_sdate in", values, "oSdate");
            return (Criteria) this;
        }

        public Criteria andOSdateNotIn(List<Date> values) {
            addCriterion("o_sdate not in", values, "oSdate");
            return (Criteria) this;
        }

        public Criteria andOSdateBetween(Date value1, Date value2) {
            addCriterion("o_sdate between", value1, value2, "oSdate");
            return (Criteria) this;
        }

        public Criteria andOSdateNotBetween(Date value1, Date value2) {
            addCriterion("o_sdate not between", value1, value2, "oSdate");
            return (Criteria) this;
        }

        public Criteria andOStatusIsNull() {
            addCriterion("o_status is null");
            return (Criteria) this;
        }

        public Criteria andOStatusIsNotNull() {
            addCriterion("o_status is not null");
            return (Criteria) this;
        }

        public Criteria andOStatusEqualTo(Integer value) {
            addCriterion("o_status =", value, "oStatus");
            return (Criteria) this;
        }

        public Criteria andOStatusNotEqualTo(Integer value) {
            addCriterion("o_status <>", value, "oStatus");
            return (Criteria) this;
        }

        public Criteria andOStatusGreaterThan(Integer value) {
            addCriterion("o_status >", value, "oStatus");
            return (Criteria) this;
        }

        public Criteria andOStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("o_status >=", value, "oStatus");
            return (Criteria) this;
        }

        public Criteria andOStatusLessThan(Integer value) {
            addCriterion("o_status <", value, "oStatus");
            return (Criteria) this;
        }

        public Criteria andOStatusLessThanOrEqualTo(Integer value) {
            addCriterion("o_status <=", value, "oStatus");
            return (Criteria) this;
        }

        public Criteria andOStatusIn(List<Integer> values) {
            addCriterion("o_status in", values, "oStatus");
            return (Criteria) this;
        }

        public Criteria andOStatusNotIn(List<Integer> values) {
            addCriterion("o_status not in", values, "oStatus");
            return (Criteria) this;
        }

        public Criteria andOStatusBetween(Integer value1, Integer value2) {
            addCriterion("o_status between", value1, value2, "oStatus");
            return (Criteria) this;
        }

        public Criteria andOStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("o_status not between", value1, value2, "oStatus");
            return (Criteria) this;
        }

        public Criteria andOSstatusIsNull() {
            addCriterion("o_sstatus is null");
            return (Criteria) this;
        }

        public Criteria andOSstatusIsNotNull() {
            addCriterion("o_sstatus is not null");
            return (Criteria) this;
        }

        public Criteria andOSstatusEqualTo(Integer value) {
            addCriterion("o_sstatus =", value, "oSstatus");
            return (Criteria) this;
        }

        public Criteria andOSstatusNotEqualTo(Integer value) {
            addCriterion("o_sstatus <>", value, "oSstatus");
            return (Criteria) this;
        }

        public Criteria andOSstatusGreaterThan(Integer value) {
            addCriterion("o_sstatus >", value, "oSstatus");
            return (Criteria) this;
        }

        public Criteria andOSstatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("o_sstatus >=", value, "oSstatus");
            return (Criteria) this;
        }

        public Criteria andOSstatusLessThan(Integer value) {
            addCriterion("o_sstatus <", value, "oSstatus");
            return (Criteria) this;
        }

        public Criteria andOSstatusLessThanOrEqualTo(Integer value) {
            addCriterion("o_sstatus <=", value, "oSstatus");
            return (Criteria) this;
        }

        public Criteria andOSstatusIn(List<Integer> values) {
            addCriterion("o_sstatus in", values, "oSstatus");
            return (Criteria) this;
        }

        public Criteria andOSstatusNotIn(List<Integer> values) {
            addCriterion("o_sstatus not in", values, "oSstatus");
            return (Criteria) this;
        }

        public Criteria andOSstatusBetween(Integer value1, Integer value2) {
            addCriterion("o_sstatus between", value1, value2, "oSstatus");
            return (Criteria) this;
        }

        public Criteria andOSstatusNotBetween(Integer value1, Integer value2) {
            addCriterion("o_sstatus not between", value1, value2, "oSstatus");
            return (Criteria) this;
        }

        public Criteria andOCodeIsNull() {
            addCriterion("o_code is null");
            return (Criteria) this;
        }

        public Criteria andOCodeIsNotNull() {
            addCriterion("o_code is not null");
            return (Criteria) this;
        }

        public Criteria andOCodeEqualTo(String value) {
            addCriterion("o_code =", value, "oCode");
            return (Criteria) this;
        }

        public Criteria andOCodeNotEqualTo(String value) {
            addCriterion("o_code <>", value, "oCode");
            return (Criteria) this;
        }

        public Criteria andOCodeGreaterThan(String value) {
            addCriterion("o_code >", value, "oCode");
            return (Criteria) this;
        }

        public Criteria andOCodeGreaterThanOrEqualTo(String value) {
            addCriterion("o_code >=", value, "oCode");
            return (Criteria) this;
        }

        public Criteria andOCodeLessThan(String value) {
            addCriterion("o_code <", value, "oCode");
            return (Criteria) this;
        }

        public Criteria andOCodeLessThanOrEqualTo(String value) {
            addCriterion("o_code <=", value, "oCode");
            return (Criteria) this;
        }

        public Criteria andOCodeLike(String value) {
            addCriterion("o_code like", value, "oCode");
            return (Criteria) this;
        }

        public Criteria andOCodeNotLike(String value) {
            addCriterion("o_code not like", value, "oCode");
            return (Criteria) this;
        }

        public Criteria andOCodeIn(List<String> values) {
            addCriterion("o_code in", values, "oCode");
            return (Criteria) this;
        }

        public Criteria andOCodeNotIn(List<String> values) {
            addCriterion("o_code not in", values, "oCode");
            return (Criteria) this;
        }

        public Criteria andOCodeBetween(String value1, String value2) {
            addCriterion("o_code between", value1, value2, "oCode");
            return (Criteria) this;
        }

        public Criteria andOCodeNotBetween(String value1, String value2) {
            addCriterion("o_code not between", value1, value2, "oCode");
            return (Criteria) this;
        }

        public Criteria andOTempIsNull() {
            addCriterion("o_temp is null");
            return (Criteria) this;
        }

        public Criteria andOTempIsNotNull() {
            addCriterion("o_temp is not null");
            return (Criteria) this;
        }

        public Criteria andOTempEqualTo(String value) {
            addCriterion("o_temp =", value, "oTemp");
            return (Criteria) this;
        }

        public Criteria andOTempNotEqualTo(String value) {
            addCriterion("o_temp <>", value, "oTemp");
            return (Criteria) this;
        }

        public Criteria andOTempGreaterThan(String value) {
            addCriterion("o_temp >", value, "oTemp");
            return (Criteria) this;
        }

        public Criteria andOTempGreaterThanOrEqualTo(String value) {
            addCriterion("o_temp >=", value, "oTemp");
            return (Criteria) this;
        }

        public Criteria andOTempLessThan(String value) {
            addCriterion("o_temp <", value, "oTemp");
            return (Criteria) this;
        }

        public Criteria andOTempLessThanOrEqualTo(String value) {
            addCriterion("o_temp <=", value, "oTemp");
            return (Criteria) this;
        }

        public Criteria andOTempLike(String value) {
            addCriterion("o_temp like", value, "oTemp");
            return (Criteria) this;
        }

        public Criteria andOTempNotLike(String value) {
            addCriterion("o_temp not like", value, "oTemp");
            return (Criteria) this;
        }

        public Criteria andOTempIn(List<String> values) {
            addCriterion("o_temp in", values, "oTemp");
            return (Criteria) this;
        }

        public Criteria andOTempNotIn(List<String> values) {
            addCriterion("o_temp not in", values, "oTemp");
            return (Criteria) this;
        }

        public Criteria andOTempBetween(String value1, String value2) {
            addCriterion("o_temp between", value1, value2, "oTemp");
            return (Criteria) this;
        }

        public Criteria andOTempNotBetween(String value1, String value2) {
            addCriterion("o_temp not between", value1, value2, "oTemp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}