package com.ll.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderitemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderitem
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderitem
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderitem
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbggenerated
     */
    public OrderitemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orderitem
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOiIdIsNull() {
            addCriterion("oi_id is null");
            return (Criteria) this;
        }

        public Criteria andOiIdIsNotNull() {
            addCriterion("oi_id is not null");
            return (Criteria) this;
        }

        public Criteria andOiIdEqualTo(Integer value) {
            addCriterion("oi_id =", value, "oiId");
            return (Criteria) this;
        }

        public Criteria andOiIdNotEqualTo(Integer value) {
            addCriterion("oi_id <>", value, "oiId");
            return (Criteria) this;
        }

        public Criteria andOiIdGreaterThan(Integer value) {
            addCriterion("oi_id >", value, "oiId");
            return (Criteria) this;
        }

        public Criteria andOiIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("oi_id >=", value, "oiId");
            return (Criteria) this;
        }

        public Criteria andOiIdLessThan(Integer value) {
            addCriterion("oi_id <", value, "oiId");
            return (Criteria) this;
        }

        public Criteria andOiIdLessThanOrEqualTo(Integer value) {
            addCriterion("oi_id <=", value, "oiId");
            return (Criteria) this;
        }

        public Criteria andOiIdIn(List<Integer> values) {
            addCriterion("oi_id in", values, "oiId");
            return (Criteria) this;
        }

        public Criteria andOiIdNotIn(List<Integer> values) {
            addCriterion("oi_id not in", values, "oiId");
            return (Criteria) this;
        }

        public Criteria andOiIdBetween(Integer value1, Integer value2) {
            addCriterion("oi_id between", value1, value2, "oiId");
            return (Criteria) this;
        }

        public Criteria andOiIdNotBetween(Integer value1, Integer value2) {
            addCriterion("oi_id not between", value1, value2, "oiId");
            return (Criteria) this;
        }

        public Criteria andOIdIsNull() {
            addCriterion("o_id is null");
            return (Criteria) this;
        }

        public Criteria andOIdIsNotNull() {
            addCriterion("o_id is not null");
            return (Criteria) this;
        }

        public Criteria andOIdEqualTo(Integer value) {
            addCriterion("o_id =", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotEqualTo(Integer value) {
            addCriterion("o_id <>", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdGreaterThan(Integer value) {
            addCriterion("o_id >", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("o_id >=", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdLessThan(Integer value) {
            addCriterion("o_id <", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdLessThanOrEqualTo(Integer value) {
            addCriterion("o_id <=", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdIn(List<Integer> values) {
            addCriterion("o_id in", values, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotIn(List<Integer> values) {
            addCriterion("o_id not in", values, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdBetween(Integer value1, Integer value2) {
            addCriterion("o_id between", value1, value2, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotBetween(Integer value1, Integer value2) {
            addCriterion("o_id not between", value1, value2, "oId");
            return (Criteria) this;
        }

        public Criteria andFIdIsNull() {
            addCriterion("f_id is null");
            return (Criteria) this;
        }

        public Criteria andFIdIsNotNull() {
            addCriterion("f_id is not null");
            return (Criteria) this;
        }

        public Criteria andFIdEqualTo(Integer value) {
            addCriterion("f_id =", value, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdNotEqualTo(Integer value) {
            addCriterion("f_id <>", value, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdGreaterThan(Integer value) {
            addCriterion("f_id >", value, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_id >=", value, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdLessThan(Integer value) {
            addCriterion("f_id <", value, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdLessThanOrEqualTo(Integer value) {
            addCriterion("f_id <=", value, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdIn(List<Integer> values) {
            addCriterion("f_id in", values, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdNotIn(List<Integer> values) {
            addCriterion("f_id not in", values, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdBetween(Integer value1, Integer value2) {
            addCriterion("f_id between", value1, value2, "fId");
            return (Criteria) this;
        }

        public Criteria andFIdNotBetween(Integer value1, Integer value2) {
            addCriterion("f_id not between", value1, value2, "fId");
            return (Criteria) this;
        }

        public Criteria andSIdIsNull() {
            addCriterion("s_id is null");
            return (Criteria) this;
        }

        public Criteria andSIdIsNotNull() {
            addCriterion("s_id is not null");
            return (Criteria) this;
        }

        public Criteria andSIdEqualTo(Integer value) {
            addCriterion("s_id =", value, "sId");
            return (Criteria) this;
        }

        public Criteria andSIdNotEqualTo(Integer value) {
            addCriterion("s_id <>", value, "sId");
            return (Criteria) this;
        }

        public Criteria andSIdGreaterThan(Integer value) {
            addCriterion("s_id >", value, "sId");
            return (Criteria) this;
        }

        public Criteria andSIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("s_id >=", value, "sId");
            return (Criteria) this;
        }

        public Criteria andSIdLessThan(Integer value) {
            addCriterion("s_id <", value, "sId");
            return (Criteria) this;
        }

        public Criteria andSIdLessThanOrEqualTo(Integer value) {
            addCriterion("s_id <=", value, "sId");
            return (Criteria) this;
        }

        public Criteria andSIdIn(List<Integer> values) {
            addCriterion("s_id in", values, "sId");
            return (Criteria) this;
        }

        public Criteria andSIdNotIn(List<Integer> values) {
            addCriterion("s_id not in", values, "sId");
            return (Criteria) this;
        }

        public Criteria andSIdBetween(Integer value1, Integer value2) {
            addCriterion("s_id between", value1, value2, "sId");
            return (Criteria) this;
        }

        public Criteria andSIdNotBetween(Integer value1, Integer value2) {
            addCriterion("s_id not between", value1, value2, "sId");
            return (Criteria) this;
        }

        public Criteria andCNameIsNull() {
            addCriterion("c_name is null");
            return (Criteria) this;
        }

        public Criteria andCNameIsNotNull() {
            addCriterion("c_name is not null");
            return (Criteria) this;
        }

        public Criteria andCNameEqualTo(String value) {
            addCriterion("c_name =", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotEqualTo(String value) {
            addCriterion("c_name <>", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameGreaterThan(String value) {
            addCriterion("c_name >", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameGreaterThanOrEqualTo(String value) {
            addCriterion("c_name >=", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameLessThan(String value) {
            addCriterion("c_name <", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameLessThanOrEqualTo(String value) {
            addCriterion("c_name <=", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameLike(String value) {
            addCriterion("c_name like", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotLike(String value) {
            addCriterion("c_name not like", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameIn(List<String> values) {
            addCriterion("c_name in", values, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotIn(List<String> values) {
            addCriterion("c_name not in", values, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameBetween(String value1, String value2) {
            addCriterion("c_name between", value1, value2, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotBetween(String value1, String value2) {
            addCriterion("c_name not between", value1, value2, "cName");
            return (Criteria) this;
        }

        public Criteria andOiPriceIsNull() {
            addCriterion("oi_price is null");
            return (Criteria) this;
        }

        public Criteria andOiPriceIsNotNull() {
            addCriterion("oi_price is not null");
            return (Criteria) this;
        }

        public Criteria andOiPriceEqualTo(Double value) {
            addCriterion("oi_price =", value, "oiPrice");
            return (Criteria) this;
        }

        public Criteria andOiPriceNotEqualTo(Double value) {
            addCriterion("oi_price <>", value, "oiPrice");
            return (Criteria) this;
        }

        public Criteria andOiPriceGreaterThan(Double value) {
            addCriterion("oi_price >", value, "oiPrice");
            return (Criteria) this;
        }

        public Criteria andOiPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("oi_price >=", value, "oiPrice");
            return (Criteria) this;
        }

        public Criteria andOiPriceLessThan(Double value) {
            addCriterion("oi_price <", value, "oiPrice");
            return (Criteria) this;
        }

        public Criteria andOiPriceLessThanOrEqualTo(Double value) {
            addCriterion("oi_price <=", value, "oiPrice");
            return (Criteria) this;
        }

        public Criteria andOiPriceIn(List<Double> values) {
            addCriterion("oi_price in", values, "oiPrice");
            return (Criteria) this;
        }

        public Criteria andOiPriceNotIn(List<Double> values) {
            addCriterion("oi_price not in", values, "oiPrice");
            return (Criteria) this;
        }

        public Criteria andOiPriceBetween(Double value1, Double value2) {
            addCriterion("oi_price between", value1, value2, "oiPrice");
            return (Criteria) this;
        }

        public Criteria andOiPriceNotBetween(Double value1, Double value2) {
            addCriterion("oi_price not between", value1, value2, "oiPrice");
            return (Criteria) this;
        }

        public Criteria andOiDateIsNull() {
            addCriterion("oi_date is null");
            return (Criteria) this;
        }

        public Criteria andOiDateIsNotNull() {
            addCriterion("oi_date is not null");
            return (Criteria) this;
        }

        public Criteria andOiDateEqualTo(Date value) {
            addCriterion("oi_date =", value, "oiDate");
            return (Criteria) this;
        }

        public Criteria andOiDateNotEqualTo(Date value) {
            addCriterion("oi_date <>", value, "oiDate");
            return (Criteria) this;
        }

        public Criteria andOiDateGreaterThan(Date value) {
            addCriterion("oi_date >", value, "oiDate");
            return (Criteria) this;
        }

        public Criteria andOiDateGreaterThanOrEqualTo(Date value) {
            addCriterion("oi_date >=", value, "oiDate");
            return (Criteria) this;
        }

        public Criteria andOiDateLessThan(Date value) {
            addCriterion("oi_date <", value, "oiDate");
            return (Criteria) this;
        }

        public Criteria andOiDateLessThanOrEqualTo(Date value) {
            addCriterion("oi_date <=", value, "oiDate");
            return (Criteria) this;
        }

        public Criteria andOiDateIn(List<Date> values) {
            addCriterion("oi_date in", values, "oiDate");
            return (Criteria) this;
        }

        public Criteria andOiDateNotIn(List<Date> values) {
            addCriterion("oi_date not in", values, "oiDate");
            return (Criteria) this;
        }

        public Criteria andOiDateBetween(Date value1, Date value2) {
            addCriterion("oi_date between", value1, value2, "oiDate");
            return (Criteria) this;
        }

        public Criteria andOiDateNotBetween(Date value1, Date value2) {
            addCriterion("oi_date not between", value1, value2, "oiDate");
            return (Criteria) this;
        }

        public Criteria andOiSeatIsNull() {
            addCriterion("oi_seat is null");
            return (Criteria) this;
        }

        public Criteria andOiSeatIsNotNull() {
            addCriterion("oi_seat is not null");
            return (Criteria) this;
        }

        public Criteria andOiSeatEqualTo(String value) {
            addCriterion("oi_seat =", value, "oiSeat");
            return (Criteria) this;
        }

        public Criteria andOiSeatNotEqualTo(String value) {
            addCriterion("oi_seat <>", value, "oiSeat");
            return (Criteria) this;
        }

        public Criteria andOiSeatGreaterThan(String value) {
            addCriterion("oi_seat >", value, "oiSeat");
            return (Criteria) this;
        }

        public Criteria andOiSeatGreaterThanOrEqualTo(String value) {
            addCriterion("oi_seat >=", value, "oiSeat");
            return (Criteria) this;
        }

        public Criteria andOiSeatLessThan(String value) {
            addCriterion("oi_seat <", value, "oiSeat");
            return (Criteria) this;
        }

        public Criteria andOiSeatLessThanOrEqualTo(String value) {
            addCriterion("oi_seat <=", value, "oiSeat");
            return (Criteria) this;
        }

        public Criteria andOiSeatLike(String value) {
            addCriterion("oi_seat like", value, "oiSeat");
            return (Criteria) this;
        }

        public Criteria andOiSeatNotLike(String value) {
            addCriterion("oi_seat not like", value, "oiSeat");
            return (Criteria) this;
        }

        public Criteria andOiSeatIn(List<String> values) {
            addCriterion("oi_seat in", values, "oiSeat");
            return (Criteria) this;
        }

        public Criteria andOiSeatNotIn(List<String> values) {
            addCriterion("oi_seat not in", values, "oiSeat");
            return (Criteria) this;
        }

        public Criteria andOiSeatBetween(String value1, String value2) {
            addCriterion("oi_seat between", value1, value2, "oiSeat");
            return (Criteria) this;
        }

        public Criteria andOiSeatNotBetween(String value1, String value2) {
            addCriterion("oi_seat not between", value1, value2, "oiSeat");
            return (Criteria) this;
        }

        public Criteria andOiTimeIsNull() {
            addCriterion("oi_time is null");
            return (Criteria) this;
        }

        public Criteria andOiTimeIsNotNull() {
            addCriterion("oi_time is not null");
            return (Criteria) this;
        }

        public Criteria andOiTimeEqualTo(String value) {
            addCriterion("oi_time =", value, "oiTime");
            return (Criteria) this;
        }

        public Criteria andOiTimeNotEqualTo(String value) {
            addCriterion("oi_time <>", value, "oiTime");
            return (Criteria) this;
        }

        public Criteria andOiTimeGreaterThan(String value) {
            addCriterion("oi_time >", value, "oiTime");
            return (Criteria) this;
        }

        public Criteria andOiTimeGreaterThanOrEqualTo(String value) {
            addCriterion("oi_time >=", value, "oiTime");
            return (Criteria) this;
        }

        public Criteria andOiTimeLessThan(String value) {
            addCriterion("oi_time <", value, "oiTime");
            return (Criteria) this;
        }

        public Criteria andOiTimeLessThanOrEqualTo(String value) {
            addCriterion("oi_time <=", value, "oiTime");
            return (Criteria) this;
        }

        public Criteria andOiTimeLike(String value) {
            addCriterion("oi_time like", value, "oiTime");
            return (Criteria) this;
        }

        public Criteria andOiTimeNotLike(String value) {
            addCriterion("oi_time not like", value, "oiTime");
            return (Criteria) this;
        }

        public Criteria andOiTimeIn(List<String> values) {
            addCriterion("oi_time in", values, "oiTime");
            return (Criteria) this;
        }

        public Criteria andOiTimeNotIn(List<String> values) {
            addCriterion("oi_time not in", values, "oiTime");
            return (Criteria) this;
        }

        public Criteria andOiTimeBetween(String value1, String value2) {
            addCriterion("oi_time between", value1, value2, "oiTime");
            return (Criteria) this;
        }

        public Criteria andOiTimeNotBetween(String value1, String value2) {
            addCriterion("oi_time not between", value1, value2, "oiTime");
            return (Criteria) this;
        }

        public Criteria andOiTempIsNull() {
            addCriterion("oi_temp is null");
            return (Criteria) this;
        }

        public Criteria andOiTempIsNotNull() {
            addCriterion("oi_temp is not null");
            return (Criteria) this;
        }

        public Criteria andOiTempEqualTo(String value) {
            addCriterion("oi_temp =", value, "oiTemp");
            return (Criteria) this;
        }

        public Criteria andOiTempNotEqualTo(String value) {
            addCriterion("oi_temp <>", value, "oiTemp");
            return (Criteria) this;
        }

        public Criteria andOiTempGreaterThan(String value) {
            addCriterion("oi_temp >", value, "oiTemp");
            return (Criteria) this;
        }

        public Criteria andOiTempGreaterThanOrEqualTo(String value) {
            addCriterion("oi_temp >=", value, "oiTemp");
            return (Criteria) this;
        }

        public Criteria andOiTempLessThan(String value) {
            addCriterion("oi_temp <", value, "oiTemp");
            return (Criteria) this;
        }

        public Criteria andOiTempLessThanOrEqualTo(String value) {
            addCriterion("oi_temp <=", value, "oiTemp");
            return (Criteria) this;
        }

        public Criteria andOiTempLike(String value) {
            addCriterion("oi_temp like", value, "oiTemp");
            return (Criteria) this;
        }

        public Criteria andOiTempNotLike(String value) {
            addCriterion("oi_temp not like", value, "oiTemp");
            return (Criteria) this;
        }

        public Criteria andOiTempIn(List<String> values) {
            addCriterion("oi_temp in", values, "oiTemp");
            return (Criteria) this;
        }

        public Criteria andOiTempNotIn(List<String> values) {
            addCriterion("oi_temp not in", values, "oiTemp");
            return (Criteria) this;
        }

        public Criteria andOiTempBetween(String value1, String value2) {
            addCriterion("oi_temp between", value1, value2, "oiTemp");
            return (Criteria) this;
        }

        public Criteria andOiTempNotBetween(String value1, String value2) {
            addCriterion("oi_temp not between", value1, value2, "oiTemp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orderitem
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orderitem
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}