package com.ll.po;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o_id
     *
     * @mbggenerated
     */
    private Integer oId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.u_id
     *
     * @mbggenerated
     */
    private Integer uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.s_id
     *
     * @mbggenerated
     */
    private Integer sId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.f_id
     *
     * @mbggenerated
     */
    private Integer fId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o_num
     *
     * @mbggenerated
     */
    private Integer oNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o_price
     *
     * @mbggenerated
     */
    private Double oPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o_seat
     *
     * @mbggenerated
     */
    private String oSeat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o_sdate
     *
     * @mbggenerated
     */
    private Date oSdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o_status
     *
     * @mbggenerated
     */
    private Integer oStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o_sstatus
     *
     * @mbggenerated
     */
    private Integer oSstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o_code
     *
     * @mbggenerated
     */
    private String oCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o_temp
     *
     * @mbggenerated
     */
    private String oTemp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o_id
     *
     * @return the value of order.o_id
     *
     * @mbggenerated
     */
    public Integer getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o_id
     *
     * @param oId the value for order.o_id
     *
     * @mbggenerated
     */
    public void setoId(Integer oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.u_id
     *
     * @return the value of order.u_id
     *
     * @mbggenerated
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.u_id
     *
     * @param uId the value for order.u_id
     *
     * @mbggenerated
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.s_id
     *
     * @return the value of order.s_id
     *
     * @mbggenerated
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.s_id
     *
     * @param sId the value for order.s_id
     *
     * @mbggenerated
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.f_id
     *
     * @return the value of order.f_id
     *
     * @mbggenerated
     */
    public Integer getfId() {
        return fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.f_id
     *
     * @param fId the value for order.f_id
     *
     * @mbggenerated
     */
    public void setfId(Integer fId) {
        this.fId = fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o_num
     *
     * @return the value of order.o_num
     *
     * @mbggenerated
     */
    public Integer getoNum() {
        return oNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o_num
     *
     * @param oNum the value for order.o_num
     *
     * @mbggenerated
     */
    public void setoNum(Integer oNum) {
        this.oNum = oNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o_price
     *
     * @return the value of order.o_price
     *
     * @mbggenerated
     */
    public Double getoPrice() {
        return oPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o_price
     *
     * @param oPrice the value for order.o_price
     *
     * @mbggenerated
     */
    public void setoPrice(Double oPrice) {
        this.oPrice = oPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o_seat
     *
     * @return the value of order.o_seat
     *
     * @mbggenerated
     */
    public String getoSeat() {
        return oSeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o_seat
     *
     * @param oSeat the value for order.o_seat
     *
     * @mbggenerated
     */
    public void setoSeat(String oSeat) {
        this.oSeat = oSeat == null ? null : oSeat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o_sdate
     *
     * @return the value of order.o_sdate
     *
     * @mbggenerated
     */
    public Date getoSdate() {
        return oSdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o_sdate
     *
     * @param oSdate the value for order.o_sdate
     *
     * @mbggenerated
     */
    public void setoSdate(Date oSdate) {
        this.oSdate = oSdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o_status
     *
     * @return the value of order.o_status
     *
     * @mbggenerated
     */
    public Integer getoStatus() {
        return oStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o_status
     *
     * @param oStatus the value for order.o_status
     *
     * @mbggenerated
     */
    public void setoStatus(Integer oStatus) {
        this.oStatus = oStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o_sstatus
     *
     * @return the value of order.o_sstatus
     *
     * @mbggenerated
     */
    public Integer getoSstatus() {
        return oSstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o_sstatus
     *
     * @param oSstatus the value for order.o_sstatus
     *
     * @mbggenerated
     */
    public void setoSstatus(Integer oSstatus) {
        this.oSstatus = oSstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o_code
     *
     * @return the value of order.o_code
     *
     * @mbggenerated
     */
    public String getoCode() {
        return oCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o_code
     *
     * @param oCode the value for order.o_code
     *
     * @mbggenerated
     */
    public void setoCode(String oCode) {
        this.oCode = oCode == null ? null : oCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o_temp
     *
     * @return the value of order.o_temp
     *
     * @mbggenerated
     */
    public String getoTemp() {
        return oTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o_temp
     *
     * @param oTemp the value for order.o_temp
     *
     * @mbggenerated
     */
    public void setoTemp(String oTemp) {
        this.oTemp = oTemp == null ? null : oTemp.trim();
    }
}