package com.ll.po;

import java.util.Date;

public class Session {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session.s_id
     *
     * @mbggenerated
     */
    private Integer sId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session.f_id
     *
     * @mbggenerated
     */
    private Integer fId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session.c_id
     *
     * @mbggenerated
     */
    private Integer cId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session.h_id
     *
     * @mbggenerated
     */
    private Integer hId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session.s_price
     *
     * @mbggenerated
     */
    private Double sPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session.s_language
     *
     * @mbggenerated
     */
    private String sLanguage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session.s_date
     *
     * @mbggenerated
     */
    private Date sDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session.s_time
     *
     * @mbggenerated
     */
    private String sTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column session.s_temp
     *
     * @mbggenerated
     */
    private String sTemp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session.s_id
     *
     * @return the value of session.s_id
     *
     * @mbggenerated
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session.s_id
     *
     * @param sId the value for session.s_id
     *
     * @mbggenerated
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session.f_id
     *
     * @return the value of session.f_id
     *
     * @mbggenerated
     */
    public Integer getfId() {
        return fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session.f_id
     *
     * @param fId the value for session.f_id
     *
     * @mbggenerated
     */
    public void setfId(Integer fId) {
        this.fId = fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session.c_id
     *
     * @return the value of session.c_id
     *
     * @mbggenerated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session.c_id
     *
     * @param cId the value for session.c_id
     *
     * @mbggenerated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session.h_id
     *
     * @return the value of session.h_id
     *
     * @mbggenerated
     */
    public Integer gethId() {
        return hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session.h_id
     *
     * @param hId the value for session.h_id
     *
     * @mbggenerated
     */
    public void sethId(Integer hId) {
        this.hId = hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session.s_price
     *
     * @return the value of session.s_price
     *
     * @mbggenerated
     */
    public Double getsPrice() {
        return sPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session.s_price
     *
     * @param sPrice the value for session.s_price
     *
     * @mbggenerated
     */
    public void setsPrice(Double sPrice) {
        this.sPrice = sPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session.s_language
     *
     * @return the value of session.s_language
     *
     * @mbggenerated
     */
    public String getsLanguage() {
        return sLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session.s_language
     *
     * @param sLanguage the value for session.s_language
     *
     * @mbggenerated
     */
    public void setsLanguage(String sLanguage) {
        this.sLanguage = sLanguage == null ? null : sLanguage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session.s_date
     *
     * @return the value of session.s_date
     *
     * @mbggenerated
     */
    public Date getsDate() {
        return sDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session.s_date
     *
     * @param sDate the value for session.s_date
     *
     * @mbggenerated
     */
    public void setsDate(Date sDate) {
        this.sDate = sDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session.s_time
     *
     * @return the value of session.s_time
     *
     * @mbggenerated
     */
    public String getsTime() {
        return sTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session.s_time
     *
     * @param sTime the value for session.s_time
     *
     * @mbggenerated
     */
    public void setsTime(String sTime) {
        this.sTime = sTime == null ? null : sTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column session.s_temp
     *
     * @return the value of session.s_temp
     *
     * @mbggenerated
     */
    public String getsTemp() {
        return sTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column session.s_temp
     *
     * @param sTemp the value for session.s_temp
     *
     * @mbggenerated
     */
    public void setsTemp(String sTemp) {
        this.sTemp = sTemp == null ? null : sTemp.trim();
    }
}