package com.ll.po;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_id
     *
     * @mbggenerated
     */
    private Integer uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.m_id
     *
     * @mbggenerated
     */
    private Integer mId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_name
     *
     * @mbggenerated
     */
    private String uName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_pwd
     *
     * @mbggenerated
     */
    private String uPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_tel
     *
     * @mbggenerated
     */
    private String uTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_email
     *
     * @mbggenerated
     */
    private String uEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_status
     *
     * @mbggenerated
     */
    private Integer uStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_pic
     *
     * @mbggenerated
     */
    private String uPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_temp
     *
     * @mbggenerated
     */
    private String uTemp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_id
     *
     * @return the value of user.u_id
     *
     * @mbggenerated
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_id
     *
     * @param uId the value for user.u_id
     *
     * @mbggenerated
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.m_id
     *
     * @return the value of user.m_id
     *
     * @mbggenerated
     */
    public Integer getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.m_id
     *
     * @param mId the value for user.m_id
     *
     * @mbggenerated
     */
    public void setmId(Integer mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_name
     *
     * @return the value of user.u_name
     *
     * @mbggenerated
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_name
     *
     * @param uName the value for user.u_name
     *
     * @mbggenerated
     */
    public void setuName(String uName) {
        this.uName = uName == null ? null : uName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_pwd
     *
     * @return the value of user.u_pwd
     *
     * @mbggenerated
     */
    public String getuPwd() {
        return uPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_pwd
     *
     * @param uPwd the value for user.u_pwd
     *
     * @mbggenerated
     */
    public void setuPwd(String uPwd) {
        this.uPwd = uPwd == null ? null : uPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_tel
     *
     * @return the value of user.u_tel
     *
     * @mbggenerated
     */
    public String getuTel() {
        return uTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_tel
     *
     * @param uTel the value for user.u_tel
     *
     * @mbggenerated
     */
    public void setuTel(String uTel) {
        this.uTel = uTel == null ? null : uTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_email
     *
     * @return the value of user.u_email
     *
     * @mbggenerated
     */
    public String getuEmail() {
        return uEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_email
     *
     * @param uEmail the value for user.u_email
     *
     * @mbggenerated
     */
    public void setuEmail(String uEmail) {
        this.uEmail = uEmail == null ? null : uEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_status
     *
     * @return the value of user.u_status
     *
     * @mbggenerated
     */
    public Integer getuStatus() {
        return uStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_status
     *
     * @param uStatus the value for user.u_status
     *
     * @mbggenerated
     */
    public void setuStatus(Integer uStatus) {
        this.uStatus = uStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_pic
     *
     * @return the value of user.u_pic
     *
     * @mbggenerated
     */
    public String getuPic() {
        return uPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_pic
     *
     * @param uPic the value for user.u_pic
     *
     * @mbggenerated
     */
    public void setuPic(String uPic) {
        this.uPic = uPic == null ? null : uPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.code
     *
     * @return the value of user.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.code
     *
     * @param code the value for user.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_temp
     *
     * @return the value of user.u_temp
     *
     * @mbggenerated
     */
    public String getuTemp() {
        return uTemp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_temp
     *
     * @param uTemp the value for user.u_temp
     *
     * @mbggenerated
     */
    public void setuTemp(String uTemp) {
        this.uTemp = uTemp == null ? null : uTemp.trim();
    }
}