package com.ll.mapper;

import com.ll.po.Active;
import com.ll.po.ActiveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active
     *
     * @mbggenerated
     */
    int countByExample(ActiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active
     *
     * @mbggenerated
     */
    int deleteByExample(ActiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer aId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active
     *
     * @mbggenerated
     */
    int insert(Active record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active
     *
     * @mbggenerated
     */
    int insertSelective(Active record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active
     *
     * @mbggenerated
     */
    List<Active> selectByExample(ActiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active
     *
     * @mbggenerated
     */
    Active selectByPrimaryKey(Integer aId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Active record, @Param("example") ActiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Active record, @Param("example") ActiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Active record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table active
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Active record);
}