package com.ll.mapper;

import com.ll.po.Cinema;
import com.ll.po.CinemaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CinemaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema
     *
     * @mbggenerated
     */
    int countByExample(CinemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema
     *
     * @mbggenerated
     */
    int deleteByExample(CinemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema
     *
     * @mbggenerated
     */
    int insert(Cinema record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema
     *
     * @mbggenerated
     */
    int insertSelective(Cinema record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema
     *
     * @mbggenerated
     */
    List<Cinema> selectByExample(CinemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema
     *
     * @mbggenerated
     */
    Cinema selectByPrimaryKey(Integer cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Cinema record, @Param("example") CinemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Cinema record, @Param("example") CinemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Cinema record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cinema
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Cinema record);
}