package com.ll.mapper;

import com.ll.po.Hall;
import com.ll.po.HallExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HallMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated
     */
    int countByExample(HallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated
     */
    int deleteByExample(HallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer hId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated
     */
    int insert(Hall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated
     */
    int insertSelective(Hall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated
     */
    List<Hall> selectByExample(HallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated
     */
    Hall selectByPrimaryKey(Integer hId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Hall record, @Param("example") HallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Hall record, @Param("example") HallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Hall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hall
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Hall record);
}